# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at https://goreleaser.com

project_name: dns-check
env:
  - GO111MODULE=on

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    binary: dns-check
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
      - v2
      - v3
brews:
  - goarm: 7
    goamd64: v2
    tap:
      owner: chandanpasunoori
      name: homebrew-tap
      branch: main
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    commit_author:
      name: Chandan Pasunoori
      email: chandanpasunoori@gmail.com
    homepage: https://github.com/chandanpasunoori/dns-check
    description: Syncs dns records from active instances to dns zone
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - image_templates:
      - ghcr.io/chandanpasunoori/{{ .ProjectName }}:{{ .Version }}-amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/chandanpasunoori/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/chandanpasunoori/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
  - name_template: ghcr.io/chandanpasunoori/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/chandanpasunoori/{{ .ProjectName }}:{{ .Version }}-amd64
  - name_template: ghcr.io/chandanpasunoori/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/chandanpasunoori/{{ .ProjectName }}:{{ .Version }}-amd64

